apiVersion: v1
kind: Secret
metadata:
  name: github-runner-secrets
type: Opaque
stringData:
  GITHUB_URL: "https://github.com/glauciolabs"
  RUNNER_GROUP: "Default"
  RUNNER_TOKEN: "AQUAIGVUT5GJDL57IKRJLS3KUTICQ"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2xhdWNpb2NhbXBvcyIsInBhc3N3b3JkIjoiZ2hwX3g5VFhpMWRUWTFhSDZ3ZGZtQXlTODdoSDR1VVo2bzJBWGoxWSIsImVtYWlsIjoiZ2xhdWNpby5jYW1wb3NAaG90bWFpbC5jb20ifX19