name: Test Secret
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Secret length: ${#SECRET_VAL}"
        env:
          SECRET_VAL: ${{ secrets.SNYK_TOKEN }}
